version: "3.8"

services:
  db:
    image: postgres:15
    container_name: cft-postgres
    restart: always
    environment:
      POSTGRES_USER: cft
      POSTGRES_PASSWORD: cftpass
      POSTGRES_DB: cftdb
    ports:
      - "5432:5432"
    volumes:
      - cft-postgres-data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql

  cft-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cft-app
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/cftdb
      SPRING_DATASOURCE_USERNAME: cft
      SPRING_DATASOURCE_PASSWORD: cftpass
    restart: always

volumes:
  cft-postgres-data: